---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfje/cf-java-client

inputs:
- name: cf-java-client
- name: om

outputs:
- name: environment

run:
  path: cf-java-client/ci/claim-environment.sh

params:
  API_TOKEN:
  POOL:
