---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfje/cf-java-client

inputs:
- name: environment
- name: cf-java-client

run:
  path: cf-java-client/ci/unclaim-environment.sh

params:
  API_TOKEN:
