// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_message.proto

package org.cloudfoundry.client.loggregator;

public final class LoggregatorProtocolBuffers {
  private LoggregatorProtocolBuffers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LogMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:logmessage.LogMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes message = 1;</code>
     */
    boolean hasMessage();
    /**
     * <code>required bytes message = 1;</code>
     */
    com.google.protobuf.ByteString getMessage();

    /**
     * <code>required .logmessage.LogMessage.MessageType message_type = 2;</code>
     */
    boolean hasMessageType();
    /**
     * <code>required .logmessage.LogMessage.MessageType message_type = 2;</code>
     */
    org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.MessageType getMessageType();

    /**
     * <code>required sint64 timestamp = 3;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required sint64 timestamp = 3;</code>
     */
    long getTimestamp();

    /**
     * <code>required string app_id = 4;</code>
     */
    boolean hasAppId();
    /**
     * <code>required string app_id = 4;</code>
     */
    java.lang.String getAppId();
    /**
     * <code>required string app_id = 4;</code>
     */
    com.google.protobuf.ByteString
        getAppIdBytes();

    /**
     * <code>optional string source_id = 6;</code>
     */
    boolean hasSourceId();
    /**
     * <code>optional string source_id = 6;</code>
     */
    java.lang.String getSourceId();
    /**
     * <code>optional string source_id = 6;</code>
     */
    com.google.protobuf.ByteString
        getSourceIdBytes();

    /**
     * <code>repeated string drain_urls = 7;</code>
     */
    com.google.protobuf.ProtocolStringList
        getDrainUrlsList();
    /**
     * <code>repeated string drain_urls = 7;</code>
     */
    int getDrainUrlsCount();
    /**
     * <code>repeated string drain_urls = 7;</code>
     */
    java.lang.String getDrainUrls(int index);
    /**
     * <code>repeated string drain_urls = 7;</code>
     */
    com.google.protobuf.ByteString
        getDrainUrlsBytes(int index);

    /**
     * <code>optional string source_name = 8;</code>
     */
    boolean hasSourceName();
    /**
     * <code>optional string source_name = 8;</code>
     */
    java.lang.String getSourceName();
    /**
     * <code>optional string source_name = 8;</code>
     */
    com.google.protobuf.ByteString
        getSourceNameBytes();
  }
  /**
   * Protobuf type {@code logmessage.LogMessage}
   */
  public static final class LogMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:logmessage.LogMessage)
      LogMessageOrBuilder {
    // Use LogMessage.newBuilder() to construct.
    private LogMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LogMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LogMessage defaultInstance;
    public static LogMessage getDefaultInstance() {
      return defaultInstance;
    }

    public LogMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LogMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              message_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.MessageType value = org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                messageType_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readSInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              appId_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              sourceId_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                drainUrls_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              drainUrls_.add(bs);
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              sourceName_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          drainUrls_ = drainUrls_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.internal_static_logmessage_LogMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.internal_static_logmessage_LogMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.class, org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<LogMessage> PARSER =
        new com.google.protobuf.AbstractParser<LogMessage>() {
      public LogMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LogMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code logmessage.LogMessage.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OUT = 1;</code>
       */
      OUT(0, 1),
      /**
       * <code>ERR = 2;</code>
       */
      ERR(1, 2),
      ;

      /**
       * <code>OUT = 1;</code>
       */
      public static final int OUT_VALUE = 1;
      /**
       * <code>ERR = 2;</code>
       */
      public static final int ERR_VALUE = 2;


      public final int getNumber() { return value; }

      public static MessageType valueOf(int value) {
        switch (value) {
          case 1: return OUT;
          case 2: return ERR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:logmessage.LogMessage.MessageType)
    }

    private int bitField0_;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString message_;
    /**
     * <code>required bytes message = 1;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes message = 1;</code>
     */
    public com.google.protobuf.ByteString getMessage() {
      return message_;
    }

    public static final int MESSAGE_TYPE_FIELD_NUMBER = 2;
    private org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.MessageType messageType_;
    /**
     * <code>required .logmessage.LogMessage.MessageType message_type = 2;</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .logmessage.LogMessage.MessageType message_type = 2;</code>
     */
    public org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.MessageType getMessageType() {
      return messageType_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>required sint64 timestamp = 3;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required sint64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int APP_ID_FIELD_NUMBER = 4;
    private java.lang.Object appId_;
    /**
     * <code>required string app_id = 4;</code>
     */
    public boolean hasAppId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string app_id = 4;</code>
     */
    public java.lang.String getAppId() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string app_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCE_ID_FIELD_NUMBER = 6;
    private java.lang.Object sourceId_;
    /**
     * <code>optional string source_id = 6;</code>
     */
    public boolean hasSourceId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string source_id = 6;</code>
     */
    public java.lang.String getSourceId() {
      java.lang.Object ref = sourceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sourceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string source_id = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSourceIdBytes() {
      java.lang.Object ref = sourceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DRAIN_URLS_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList drainUrls_;
    /**
     * <code>repeated string drain_urls = 7;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDrainUrlsList() {
      return drainUrls_;
    }
    /**
     * <code>repeated string drain_urls = 7;</code>
     */
    public int getDrainUrlsCount() {
      return drainUrls_.size();
    }
    /**
     * <code>repeated string drain_urls = 7;</code>
     */
    public java.lang.String getDrainUrls(int index) {
      return drainUrls_.get(index);
    }
    /**
     * <code>repeated string drain_urls = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDrainUrlsBytes(int index) {
      return drainUrls_.getByteString(index);
    }

    public static final int SOURCE_NAME_FIELD_NUMBER = 8;
    private java.lang.Object sourceName_;
    /**
     * <code>optional string source_name = 8;</code>
     */
    public boolean hasSourceName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string source_name = 8;</code>
     */
    public java.lang.String getSourceName() {
      java.lang.Object ref = sourceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sourceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string source_name = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSourceNameBytes() {
      java.lang.Object ref = sourceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      message_ = com.google.protobuf.ByteString.EMPTY;
      messageType_ = org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.MessageType.OUT;
      timestamp_ = 0L;
      appId_ = "";
      sourceId_ = "";
      drainUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      sourceName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, message_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeSInt64(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getAppIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getSourceIdBytes());
      }
      for (int i = 0; i < drainUrls_.size(); i++) {
        output.writeBytes(7, drainUrls_.getByteString(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(8, getSourceNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, message_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getAppIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getSourceIdBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < drainUrls_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(drainUrls_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getDrainUrlsList().size();
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getSourceNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code logmessage.LogMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:logmessage.LogMessage)
        org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.internal_static_logmessage_LogMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.internal_static_logmessage_LogMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.class, org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.Builder.class);
      }

      // Construct using org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        message_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.MessageType.OUT;
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        appId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        sourceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        drainUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        sourceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.internal_static_logmessage_LogMessage_descriptor;
      }

      public org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage getDefaultInstanceForType() {
        return org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.getDefaultInstance();
      }

      public org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage build() {
        org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage buildPartial() {
        org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage result = new org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.appId_ = appId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sourceId_ = sourceId_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          drainUrls_ = drainUrls_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.drainUrls_ = drainUrls_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.sourceName_ = sourceName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage) {
          return mergeFrom((org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage other) {
        if (other == org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasAppId()) {
          bitField0_ |= 0x00000008;
          appId_ = other.appId_;
          onChanged();
        }
        if (other.hasSourceId()) {
          bitField0_ |= 0x00000010;
          sourceId_ = other.sourceId_;
          onChanged();
        }
        if (!other.drainUrls_.isEmpty()) {
          if (drainUrls_.isEmpty()) {
            drainUrls_ = other.drainUrls_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureDrainUrlsIsMutable();
            drainUrls_.addAll(other.drainUrls_);
          }
          onChanged();
        }
        if (other.hasSourceName()) {
          bitField0_ |= 0x00000040;
          sourceName_ = other.sourceName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessage()) {
          
          return false;
        }
        if (!hasMessageType()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasAppId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes message = 1;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes message = 1;</code>
       */
      public com.google.protobuf.ByteString getMessage() {
        return message_;
      }
      /**
       * <code>required bytes message = 1;</code>
       */
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes message = 1;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }

      private org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.MessageType messageType_ = org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.MessageType.OUT;
      /**
       * <code>required .logmessage.LogMessage.MessageType message_type = 2;</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .logmessage.LogMessage.MessageType message_type = 2;</code>
       */
      public org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.MessageType getMessageType() {
        return messageType_;
      }
      /**
       * <code>required .logmessage.LogMessage.MessageType message_type = 2;</code>
       */
      public Builder setMessageType(org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .logmessage.LogMessage.MessageType message_type = 2;</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        messageType_ = org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.MessageType.OUT;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>required sint64 timestamp = 3;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required sint64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required sint64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sint64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object appId_ = "";
      /**
       * <code>required string app_id = 4;</code>
       */
      public boolean hasAppId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string app_id = 4;</code>
       */
      public java.lang.String getAppId() {
        java.lang.Object ref = appId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            appId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string app_id = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAppIdBytes() {
        java.lang.Object ref = appId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string app_id = 4;</code>
       */
      public Builder setAppId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string app_id = 4;</code>
       */
      public Builder clearAppId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        appId_ = getDefaultInstance().getAppId();
        onChanged();
        return this;
      }
      /**
       * <code>required string app_id = 4;</code>
       */
      public Builder setAppIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        appId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sourceId_ = "";
      /**
       * <code>optional string source_id = 6;</code>
       */
      public boolean hasSourceId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string source_id = 6;</code>
       */
      public java.lang.String getSourceId() {
        java.lang.Object ref = sourceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sourceId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string source_id = 6;</code>
       */
      public com.google.protobuf.ByteString
          getSourceIdBytes() {
        java.lang.Object ref = sourceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string source_id = 6;</code>
       */
      public Builder setSourceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sourceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string source_id = 6;</code>
       */
      public Builder clearSourceId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sourceId_ = getDefaultInstance().getSourceId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string source_id = 6;</code>
       */
      public Builder setSourceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sourceId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList drainUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDrainUrlsIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          drainUrls_ = new com.google.protobuf.LazyStringArrayList(drainUrls_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string drain_urls = 7;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getDrainUrlsList() {
        return drainUrls_.getUnmodifiableView();
      }
      /**
       * <code>repeated string drain_urls = 7;</code>
       */
      public int getDrainUrlsCount() {
        return drainUrls_.size();
      }
      /**
       * <code>repeated string drain_urls = 7;</code>
       */
      public java.lang.String getDrainUrls(int index) {
        return drainUrls_.get(index);
      }
      /**
       * <code>repeated string drain_urls = 7;</code>
       */
      public com.google.protobuf.ByteString
          getDrainUrlsBytes(int index) {
        return drainUrls_.getByteString(index);
      }
      /**
       * <code>repeated string drain_urls = 7;</code>
       */
      public Builder setDrainUrls(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDrainUrlsIsMutable();
        drainUrls_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string drain_urls = 7;</code>
       */
      public Builder addDrainUrls(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDrainUrlsIsMutable();
        drainUrls_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string drain_urls = 7;</code>
       */
      public Builder addAllDrainUrls(
          java.lang.Iterable<java.lang.String> values) {
        ensureDrainUrlsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, drainUrls_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string drain_urls = 7;</code>
       */
      public Builder clearDrainUrls() {
        drainUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string drain_urls = 7;</code>
       */
      public Builder addDrainUrlsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDrainUrlsIsMutable();
        drainUrls_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object sourceName_ = "";
      /**
       * <code>optional string source_name = 8;</code>
       */
      public boolean hasSourceName() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string source_name = 8;</code>
       */
      public java.lang.String getSourceName() {
        java.lang.Object ref = sourceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sourceName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string source_name = 8;</code>
       */
      public com.google.protobuf.ByteString
          getSourceNameBytes() {
        java.lang.Object ref = sourceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string source_name = 8;</code>
       */
      public Builder setSourceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        sourceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string source_name = 8;</code>
       */
      public Builder clearSourceName() {
        bitField0_ = (bitField0_ & ~0x00000040);
        sourceName_ = getDefaultInstance().getSourceName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string source_name = 8;</code>
       */
      public Builder setSourceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        sourceName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:logmessage.LogMessage)
    }

    static {
      defaultInstance = new LogMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:logmessage.LogMessage)
  }

  public interface LogEnvelopeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:logmessage.LogEnvelope)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string routing_key = 1;</code>
     */
    boolean hasRoutingKey();
    /**
     * <code>required string routing_key = 1;</code>
     */
    java.lang.String getRoutingKey();
    /**
     * <code>required string routing_key = 1;</code>
     */
    com.google.protobuf.ByteString
        getRoutingKeyBytes();

    /**
     * <code>required bytes signature = 2;</code>
     */
    boolean hasSignature();
    /**
     * <code>required bytes signature = 2;</code>
     */
    com.google.protobuf.ByteString getSignature();

    /**
     * <code>required .logmessage.LogMessage log_message = 3;</code>
     */
    boolean hasLogMessage();
    /**
     * <code>required .logmessage.LogMessage log_message = 3;</code>
     */
    org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage getLogMessage();
    /**
     * <code>required .logmessage.LogMessage log_message = 3;</code>
     */
    org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessageOrBuilder getLogMessageOrBuilder();
  }
  /**
   * Protobuf type {@code logmessage.LogEnvelope}
   */
  public static final class LogEnvelope extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:logmessage.LogEnvelope)
      LogEnvelopeOrBuilder {
    // Use LogEnvelope.newBuilder() to construct.
    private LogEnvelope(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LogEnvelope(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LogEnvelope defaultInstance;
    public static LogEnvelope getDefaultInstance() {
      return defaultInstance;
    }

    public LogEnvelope getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LogEnvelope(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              routingKey_ = bs;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              signature_ = input.readBytes();
              break;
            }
            case 26: {
              org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = logMessage_.toBuilder();
              }
              logMessage_ = input.readMessage(org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(logMessage_);
                logMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.internal_static_logmessage_LogEnvelope_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.internal_static_logmessage_LogEnvelope_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope.class, org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope.Builder.class);
    }

    public static com.google.protobuf.Parser<LogEnvelope> PARSER =
        new com.google.protobuf.AbstractParser<LogEnvelope>() {
      public LogEnvelope parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogEnvelope(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LogEnvelope> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ROUTING_KEY_FIELD_NUMBER = 1;
    private java.lang.Object routingKey_;
    /**
     * <code>required string routing_key = 1;</code>
     */
    public boolean hasRoutingKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string routing_key = 1;</code>
     */
    public java.lang.String getRoutingKey() {
      java.lang.Object ref = routingKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          routingKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string routing_key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRoutingKeyBytes() {
      java.lang.Object ref = routingKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        routingKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>required bytes signature = 2;</code>
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes signature = 2;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    public static final int LOG_MESSAGE_FIELD_NUMBER = 3;
    private org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage logMessage_;
    /**
     * <code>required .logmessage.LogMessage log_message = 3;</code>
     */
    public boolean hasLogMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .logmessage.LogMessage log_message = 3;</code>
     */
    public org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage getLogMessage() {
      return logMessage_;
    }
    /**
     * <code>required .logmessage.LogMessage log_message = 3;</code>
     */
    public org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessageOrBuilder getLogMessageOrBuilder() {
      return logMessage_;
    }

    private void initFields() {
      routingKey_ = "";
      signature_ = com.google.protobuf.ByteString.EMPTY;
      logMessage_ = org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRoutingKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSignature()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLogMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getLogMessage().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRoutingKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, signature_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, logMessage_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRoutingKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, signature_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, logMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code logmessage.LogEnvelope}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:logmessage.LogEnvelope)
        org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelopeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.internal_static_logmessage_LogEnvelope_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.internal_static_logmessage_LogEnvelope_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope.class, org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope.Builder.class);
      }

      // Construct using org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLogMessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        routingKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        signature_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (logMessageBuilder_ == null) {
          logMessage_ = org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.getDefaultInstance();
        } else {
          logMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.internal_static_logmessage_LogEnvelope_descriptor;
      }

      public org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope getDefaultInstanceForType() {
        return org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope.getDefaultInstance();
      }

      public org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope build() {
        org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope buildPartial() {
        org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope result = new org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.routingKey_ = routingKey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.signature_ = signature_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (logMessageBuilder_ == null) {
          result.logMessage_ = logMessage_;
        } else {
          result.logMessage_ = logMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope) {
          return mergeFrom((org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope other) {
        if (other == org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope.getDefaultInstance()) return this;
        if (other.hasRoutingKey()) {
          bitField0_ |= 0x00000001;
          routingKey_ = other.routingKey_;
          onChanged();
        }
        if (other.hasSignature()) {
          setSignature(other.getSignature());
        }
        if (other.hasLogMessage()) {
          mergeLogMessage(other.getLogMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRoutingKey()) {
          
          return false;
        }
        if (!hasSignature()) {
          
          return false;
        }
        if (!hasLogMessage()) {
          
          return false;
        }
        if (!getLogMessage().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogEnvelope) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object routingKey_ = "";
      /**
       * <code>required string routing_key = 1;</code>
       */
      public boolean hasRoutingKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string routing_key = 1;</code>
       */
      public java.lang.String getRoutingKey() {
        java.lang.Object ref = routingKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            routingKey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string routing_key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRoutingKeyBytes() {
        java.lang.Object ref = routingKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          routingKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string routing_key = 1;</code>
       */
      public Builder setRoutingKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        routingKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string routing_key = 1;</code>
       */
      public Builder clearRoutingKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        routingKey_ = getDefaultInstance().getRoutingKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string routing_key = 1;</code>
       */
      public Builder setRoutingKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        routingKey_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes signature = 2;</code>
       */
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes signature = 2;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>required bytes signature = 2;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes signature = 2;</code>
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000002);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }

      private org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage logMessage_ = org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage, org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.Builder, org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessageOrBuilder> logMessageBuilder_;
      /**
       * <code>required .logmessage.LogMessage log_message = 3;</code>
       */
      public boolean hasLogMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .logmessage.LogMessage log_message = 3;</code>
       */
      public org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage getLogMessage() {
        if (logMessageBuilder_ == null) {
          return logMessage_;
        } else {
          return logMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>required .logmessage.LogMessage log_message = 3;</code>
       */
      public Builder setLogMessage(org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage value) {
        if (logMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          logMessage_ = value;
          onChanged();
        } else {
          logMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .logmessage.LogMessage log_message = 3;</code>
       */
      public Builder setLogMessage(
          org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.Builder builderForValue) {
        if (logMessageBuilder_ == null) {
          logMessage_ = builderForValue.build();
          onChanged();
        } else {
          logMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .logmessage.LogMessage log_message = 3;</code>
       */
      public Builder mergeLogMessage(org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage value) {
        if (logMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              logMessage_ != org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.getDefaultInstance()) {
            logMessage_ =
              org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.newBuilder(logMessage_).mergeFrom(value).buildPartial();
          } else {
            logMessage_ = value;
          }
          onChanged();
        } else {
          logMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .logmessage.LogMessage log_message = 3;</code>
       */
      public Builder clearLogMessage() {
        if (logMessageBuilder_ == null) {
          logMessage_ = org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.getDefaultInstance();
          onChanged();
        } else {
          logMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .logmessage.LogMessage log_message = 3;</code>
       */
      public org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.Builder getLogMessageBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getLogMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>required .logmessage.LogMessage log_message = 3;</code>
       */
      public org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessageOrBuilder getLogMessageOrBuilder() {
        if (logMessageBuilder_ != null) {
          return logMessageBuilder_.getMessageOrBuilder();
        } else {
          return logMessage_;
        }
      }
      /**
       * <code>required .logmessage.LogMessage log_message = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage, org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.Builder, org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessageOrBuilder> 
          getLogMessageFieldBuilder() {
        if (logMessageBuilder_ == null) {
          logMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage, org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessage.Builder, org.cloudfoundry.client.loggregator.LoggregatorProtocolBuffers.LogMessageOrBuilder>(
                  getLogMessage(),
                  getParentForChildren(),
                  isClean());
          logMessage_ = null;
        }
        return logMessageBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:logmessage.LogEnvelope)
    }

    static {
      defaultInstance = new LogEnvelope(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:logmessage.LogEnvelope)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_logmessage_LogMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_logmessage_LogMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_logmessage_LogEnvelope_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_logmessage_LogEnvelope_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021log_message.proto\022\nlogmessage\"\327\001\n\nLogM" +
      "essage\022\017\n\007message\030\001 \002(\014\0228\n\014message_type\030" +
      "\002 \002(\0162\".logmessage.LogMessage.MessageTyp" +
      "e\022\021\n\ttimestamp\030\003 \002(\022\022\016\n\006app_id\030\004 \002(\t\022\021\n\t" +
      "source_id\030\006 \001(\t\022\022\n\ndrain_urls\030\007 \003(\t\022\023\n\013s" +
      "ource_name\030\010 \001(\t\"\037\n\013MessageType\022\007\n\003OUT\020\001" +
      "\022\007\n\003ERR\020\002\"b\n\013LogEnvelope\022\023\n\013routing_key\030" +
      "\001 \002(\t\022\021\n\tsignature\030\002 \002(\014\022+\n\013log_message\030" +
      "\003 \002(\0132\026.logmessage.LogMessageBA\n#org.clo" +
      "udfoundry.client.loggregatorB\032Loggregato",
      "rProtocolBuffers"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_logmessage_LogMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_logmessage_LogMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_logmessage_LogMessage_descriptor,
        new java.lang.String[] { "Message", "MessageType", "Timestamp", "AppId", "SourceId", "DrainUrls", "SourceName", });
    internal_static_logmessage_LogEnvelope_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_logmessage_LogEnvelope_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_logmessage_LogEnvelope_descriptor,
        new java.lang.String[] { "RoutingKey", "Signature", "LogMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
